INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SYNCHRONOUSLABS SynchronousLabs)

FIND_PATH(
    SYNCHRONOUSLABS_INCLUDE_DIRS
    NAMES SynchronousLabs/api.h
    HINTS $ENV{SYNCHRONOUSLABS_DIR}/include
        ${PC_SYNCHRONOUSLABS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SYNCHRONOUSLABS_LIBRARIES
    NAMES gnuradio-SynchronousLabs
    HINTS $ENV{SYNCHRONOUSLABS_DIR}/lib
        ${PC_SYNCHRONOUSLABS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SYNCHRONOUSLABS DEFAULT_MSG SYNCHRONOUSLABS_LIBRARIES SYNCHRONOUSLABS_INCLUDE_DIRS)
MARK_AS_ADVANCED(SYNCHRONOUSLABS_LIBRARIES SYNCHRONOUSLABS_INCLUDE_DIRS)

